import React, {useCallback, useEffect, useState} from 'react';
import {ActivityIndicator, Alert, FlatList, Modal, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View} from 'react-native';
import {useIsFocused} from '@react-navigation/native';
import axios from '../api/axios';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';

const lista = data => Array.isArray(data) ? data : data?.data || [];
const Instituciones = ({navigation}) => {
  const [instituciones,setInstituciones]=useState([]),[nombre,setNombre]=useState(''),[estado,setEstado]=useState(true),[id,setId]=useState(null),[visible,setVisible]=useState(false),[cargando,setCargando]=useState(false); const focus=useIsFocused();
  const cargar=useCallback(async()=>{setCargando(true);try{const {data}=await axios.get('instituciones');setInstituciones(lista(data));}catch(error){Alert.alert('Error',error.response?.data?.message||'No se pudo cargar instituciones.');}finally{setCargando(false);}},[]);
  useEffect(()=>{if(focus)cargar();},[focus,cargar]);
  const abrir=item=>{setId(item?.id||null);setNombre(item?.nombre||'');setEstado(item?.estado??true);setVisible(true);};
  const guardar=async()=>{if(!nombre.trim()){Alert.alert('Campo requerido','Ingresa el nombre de la institución.');return;}setCargando(true);try{const datos={nombre:nombre.trim(),estado};if(id)await axios.put(`instituciones/${id}`,datos);else await axios.post('instituciones',datos);setVisible(false);await cargar();}catch(error){Alert.alert('No se pudo guardar',error.response?.data?.message||'Inténtalo nuevamente.');}finally{setCargando(false);}};
  const eliminar=item=>Alert.alert('Eliminar institución',`¿Eliminar "${item.nombre}"?`,[{text:'Cancelar',style:'cancel'},{text:'Eliminar',style:'destructive',onPress:async()=>{try{await axios.delete(`instituciones/${item.id}`);await cargar();}catch(error){Alert.alert('No se pudo eliminar',error.response?.data?.message||'Esta institución podría tener pacientes asociados.');}}}]);
  return <View style={styles.container}><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()}><MaterialIcons name="arrow-back" size={28} color="#093eeb"/></TouchableOpacity><Text style={styles.title}>Instituciones</Text><TouchableOpacity onPress={()=>abrir()}><MaterialIcons name="add-business" size={28} color="#093eeb"/></TouchableOpacity></View><Text style={styles.count}>{instituciones.length} institución{instituciones.length===1?'':'es'}</Text>{cargando&&!visible?<ActivityIndicator size="large" color="#093eeb"/>:<FlatList data={instituciones} keyExtractor={item=>String(item.id)} refreshing={cargando} onRefresh={cargar} ListEmptyComponent={<Text style={styles.empty}>Aún no hay instituciones registradas.</Text>} renderItem={({item})=><View style={styles.card}><View><Text style={styles.name}>{item.nombre}</Text><Text style={{color:item.estado?'#27853b':'#b33'}}>Estado: {item.estado?'Activo':'Inactivo'}</Text></View><View><TouchableOpacity onPress={()=>abrir(item)}><MaterialIcons name="edit" size={25} color="#093eeb"/></TouchableOpacity><TouchableOpacity style={{marginTop:13}} onPress={()=>eliminar(item)}><MaterialIcons name="delete-outline" size={25} color="#d32f2f"/></TouchableOpacity></View></View>}/>}<Modal visible={visible} animationType="slide" transparent onRequestClose={()=>setVisible(false)}><View style={styles.overlay}><View style={styles.modal}><Text style={styles.modalTitle}>{id?'Editar institución':'Nueva institución'}</Text><Text style={styles.label}>Nombre</Text><TextInput style={styles.input} value={nombre} onChangeText={setNombre} placeholder="Nombre de institución"/><View style={styles.switchLine}><Text style={styles.label}>Activa</Text><Switch value={Boolean(estado)} onValueChange={setEstado}/></View><View style={styles.actions}><TouchableOpacity style={styles.cancel} onPress={()=>setVisible(false)}><Text>Cancelar</Text></TouchableOpacity><TouchableOpacity style={styles.save} onPress={guardar}><Text style={styles.saveText}>{cargando?'Guardando...':'Guardar'}</Text></TouchableOpacity></View></View></View></Modal></View>;
};
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#f6f5f5',padding:18},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:14,borderBottomWidth:1,borderColor:'#ddd'},title:{fontSize:22,fontWeight:'700',color:'#093eeb'},count:{marginVertical:14,color:'#555',fontWeight:'600'},card:{backgroundColor:'#fff',padding:15,marginBottom:10,borderRadius:8,flexDirection:'row',justifyContent:'space-between',elevation:2},name:{fontSize:17,fontWeight:'700',color:'#333',marginBottom:5},empty:{textAlign:'center',marginTop:40,color:'#777'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.45)',justifyContent:'center',padding:18},modal:{backgroundColor:'#fff',borderRadius:10,padding:20},modalTitle:{fontSize:20,fontWeight:'700',color:'#093eeb',marginBottom:12},label:{fontWeight:'600',marginTop:8,color:'#444'},input:{borderWidth:1,borderColor:'#c7c8cc',borderRadius:5,paddingHorizontal:10,height:43,marginTop:4},switchLine:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:14},actions:{flexDirection:'row',justifyContent:'flex-end',marginTop:20,gap:10},cancel:{padding:12},save:{backgroundColor:'#093eeb',padding:12,borderRadius:5,minWidth:90,alignItems:'center'},saveText:{color:'#fff',fontWeight:'700'}});
export default Instituciones;
