import { StyleSheet, Dimensions } from 'react-native';
const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;
import { NativeModules } from 'react-native';
const { StatusBarManager } = NativeModules;
const heightStatus = StatusBarManager.HEIGHT;

const general = {
  primaryColor: '#05C7CC',
  secondaryColor: '#FF9E14', //FF9103
  thirdColor: '#ffff',
  cardColor: '#F0F0F0',
  textButtons: '#ffff',
  errorColor: '#E94560',
  inputsColor: '#EEEEEE',
  colorbuttons: '#495464',

  colorbody: '#F6F5F5',

  colorFondo: '#EFECEC',
  colorLables: '#61677A',
  colorTextos: '#0C356A', //0C356A

  backgroundInputsForms: '#F7F7F8',
  bordercolorInputsForms: '#C7C8CC',
  // posiblecolor: 394347,
};

const LoginS = StyleSheet.create({
  container_fondo: {
    flex: 1,
    justifyContent: 'center',
  },
  imagen_fondo: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: width,
    height: height * 0.9,
  },
  container: {
    flex: 1,
    backgroundColor: '#FEFAF6',
  },
  bar: {
    height: heightStatus,
    width: width * 0.91,
  },
  container_div: {
    width: width * 0.95,
    height: height * 0.6,
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    // backgroundColor: 'red',
  },
  container_div_head: {
    width: width * 0.91,
    height: height * 0.25,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: height * 0.005,
    // backgroundColor: 'green',
  },
  container_web: {
    width: width * 0.91,
    height: height * 0.1,
    flexDirection: 'column',
    alignSelf: 'center',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  size_image: {
    width: width * 0.6,
    height: height * 0.23,
  },
  container_div_body: {
    width: width * 0.91,
    height: height * 0.2,
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: height * 0.005,
    // marginBottom:(height * 0.040),
    // backgroundColor: 'purple',
  },
  container_div_footer: {
    width: width * 0.91,
    height: height * 0.1,
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: height * 0.005,
    // marginBottom:(height * 0.040),
    // backgroundColor: 'yellow',
  },
  container_div_titulo_img: {
    width: width * 0.75,
    height: height * 0.1,
    marginBottom: height * 0.02,
    marginTop: height * 0.02,
    // borderWidth:5,
    // borderRadius:100,
    borderColor: '#05C7CC',
    // backgroundColor:'#016A70',
  },
  container_div_titulo_text: {
    fontSize: 24,
    fontWeight: '600',
    color: '#05C7CC',
  },
  container_div_titulo_text2: {
    fontSize: 24,
    fontWeight: '400',
    color: '#05C7CC',
  },
  container_div_inputs: {
    width: width * 0.91,
    height: height * 0.07,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth:1,
    // backgroundColor: '#FEF3E2',
    // marginBottom: height * 0.01,
  },
  container_div_inputs_campos: {
    width: width * 0.9,
    height: height * 0.07,
    // borderWidth: 1.5,
    // borderColor: general.secondaryColor,
    backgroundColor: 'rgba(246,246,246,1)',
    borderRadius: 5,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    flexDirection: 'row',

    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2.84,
    elevation: 5,
  },

  container_div_inputs_check: {
    width: width * 0.93,
    height: height * 0.05,
    justifyContent: 'flex-end',
    alignItems: 'baseline',
    flexDirection: 'row',
    paddingRight: 10,
    // backgroundColor:'red'
  },
  container_colores_text: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffff',
  },
  container_colores_correos: {
    fontSize: 17,
    fontWeight: '700',
    color: general.thirdColor,
    textDecorationLine: 'underline',
  },
  container_colores_correo: {
    fontSize: 17,
    fontWeight: '700',
    color: '#052F30',
  },
  container_div_inputs_campos_1: {
    width: width * 0.1,
    height: height * 0.07,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  container_div_inputs_campos_2: {
    width: width * 0.6,
    height: height * 0.07,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  container_div_inputs_campos_1_espacios: {},
  container_div_boton: {
    width: width * 0.84,
    height: height * 0.13,
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignSelf: 'center',
    alignItems: 'center',
    borderTopWidth: 2,
    borderColor: '#ffff',
    // backgroundColor:'#337CCF'
  },
  container_div_boton_boton: {
    width: width * 0.9,
    height: height * 0.07,
    // backgroundColor:general.primaryColor,
    backgroundColor: general.secondaryColor,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  container_div_boton_registrar: {
    width: width * 0.9,
    height: height * 0.18,
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignSelf: 'center',
    alignItems: 'center',
    // borderTopWidth:2,
    // borderWidth:2,
    // borderColor:'#ffff',
    borderColor: '#ffff',
  },
  container_div_boton_registrar_div1: {
    width: width * 0.8,
    height: height * 0.07,
    justifyContent: 'center',
    // backgroundColor:'#337CCF',
    alignItems: 'center',
  },
  container_div_boton_registrar_div2: {
    width: width * 0.8,
    height: height * 0.07,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container_div_boton_boton_registrar: {
    width: width * 0.4,
    height: height * 0.07,
    backgroundColor: general.primaryColor,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  container_div_boton_text: {
    fontSize: 18,
    fontWeight: '400',
    color: 'white',
  },
  Texto_color_inputs: {
    color: '#31363F',
    textAlign: 'left',
    width: width * 0.7,
    height: height * 0.06,
    // backgroundColor:'green'
  },
  Texto_color_inputs_pass: {
    color: '#31363F',
    textAlign: 'left',
    width: width * 0.7,
    height: height * 0.06,
    // backgroundColor:'green'
  },
});

const InicioS = StyleSheet.create({
  container: {
    flex: 1,
    width: width * 1,
    backgroundColor: '#FFA931',
    // backgroundColor: general.secondaryColor,
  },
  text_color_general: {
    color: general.colorTextos,
    fontSize: 14,
    fontWeight: '500',
  },
  container_head: {
    width: width * 0.97,
    height: height * 0.08,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  container_head_div: {
    width: width * 0.93,
    height: height * 0.06,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  container_menu_options_head: {
    width: width * 0.12,
    height: height * 0.06,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderRadius: 4,
  },
  text_title_head: {
    fontSize: 18,
    fontWeight: '700',
    color: general.colorTextos,
  },
  container_name_user: {
    width: width * 0.95,
    height: height * 0.05,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  container_name_user_div: {
    width: width * 0.93,
    height: height * 0.05,
    flexDirection: 'row',
    // justifyContent: 'space-around',
    alignItems: 'center',
  },
  container_body: {
    width: width * 1,
    height: height * 0.86,
    backgroundColor: general.colorbody, //#fff
    alignSelf: 'center',
    borderTopWidth: 4,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderColor: general.colorbody,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  container_div: {
    width: width * 0.97,
    height: height * 0.12,
    alignItems: 'center',
    // borderWidth:.2,
    // backgroundColor: 'green',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignSelf: 'center',
    marginTop: height * 0.01,
  },
  container_titles: {
    width: width * 0.93,
    height: height * 0.03,
    alignSelf: 'center',
    // backgroundColor: 'red',
    marginBottom: height * 0.01,
  },
  container_div_menu: {
    width: width * 0.93,
    height: height * 0.2,
    alignItems: 'center',
    // borderWidth: 1,
    backgroundColor: '#ffff',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignSelf: 'center',
    marginTop: height * 0.01,
    marginBottom: height * 0.02,
    borderRadius: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  container_div_menu_title: {
    width: width * 0.9,
    height: height * 0.03,
  },
  container_div_menu_category: {
    flexDirection: 'row',
    width: width * 0.9,
    height: height * 0.18,
    // backgroundColor: 'purple',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  container_div_menu_category_option: {
    flexDirection: 'column',
    // borderWidth: 1,
    alignItems: 'center',
    height: height * 0.17,
    justifyContent: 'space-between',
  },
  container_div_menu_category_option_div: {
    width: width * 0.07,
    height: height * 0.05,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffff',
    borderRadius: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  container_div_menu_banner: {
    width: width * 0.93,
    height: height * 0.3,
    // alignItems: 'center',
    // borderWidth: 1,
    backgroundColor: '#ffff',
    // flexDirection: 'column',
    justifyContent: 'space-between',
    alignSelf: 'center',
    marginTop: height * 0.01,
    borderRadius: 3,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  size_image_banner: {
    width: width * 0.93,
    height: height * 0.2,
    borderRadius: 8,
  },
  size_image: {
    width: width * 0.135,
    height: height * 0.065,
    borderRadius: 8,
  },
  div_opciones: {
    width: width * 0.93,
    height: height * 0.08,
    // backgroundColor: 'yellow',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  div_opciones_campo: {
    width: width * 0.19,
    height: height * 0.08,
    backgroundColor: '#FFFF',
    borderRadius: 3,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  text_titulo: {
    fontSize: 40,
    fontWeight: '500',
  },
  // MODAL GENERAL
  menu_modal_container: {
    backgroundColor: 'white',
    width: width * 0.75,
    height: height * 0.25,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    // padding: 20,
    borderRadius: 5,
  },
  menu_modal_container_option: {
    width: width * 0.75,
    height: height * 0.08,
    // backgroundColor: '#F5F5F5',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.005,
  },
  menu_modal_container_option1: {
    width: width * 0.75,
    height: height * 0.08,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.005,
    borderTopWidth: 1,
    borderColor: '#D1D1D1',
  },
  menu_modal_container_option2: {
    width: width * 0.75,
    height: height * 0.08,
    // backgroundColor: '#FF5656',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.001,
  },
  text_color_general_indicator: {
    color: general.colorTextos,
    fontSize: 20,
    fontWeight: '500',
  },
  text_color_general_modal: {
    color: '#ffff',
    fontSize: 14,
    fontWeight: '500',
  },
  text_color_general_modal_exit: {
    color: '#FF5656',
    fontSize: 14,
    fontWeight: '500',
  },
});

const CotizarS = StyleSheet.create({
  container: {
    flex: 1,
    width: width * 1,
    backgroundColor: '#ffff',
    // justifyContent: 'center',
  },
  text_color_general: {
    color: general.colorTextos,
    fontSize: 14,
    fontWeight: '500',
  },
  container_head: {
    width: width * 0.85,
    height: height * 0.08,
    marginTop: height * 0.01,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignSelf: 'center',
    // borderBottomWidth: 1,
    // borderBottomColor: general.colorbuttons,
    // backgroundColor: 'red',
  },
  container_head_opcionR: {
    width: width * 0.27,
    height: height * 0.075,
    borderColor: general.colorbuttons,
    borderWidth: 0.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menu_opciones_tabs: {
    width: width * 0.93,
    alignSelf: 'center',
  },
  container_head_div: {
    width: width * 0.93,
    height: height * 0.06,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  container_menu_options_head: {
    width: width * 0.12,
    height: height * 0.06,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  text_title_head: {
    fontSize: 18,
    fontWeight: '700',
    color: general.colorTextos,
  },
  container_name_user: {
    width: width * 0.95,
    height: height * 0.05,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },

  container_name_user_div: {
    width: width * 0.93,
    height: height * 0.05,
    flexDirection: 'row',
    // justifyContent: 'space-around',
    alignItems: 'center',
  },

  container_body: {
    width: width * 0.95,
    height: height * 0.7,
    // backgroundColor: '#f19fff',
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: height * 0.01,
  },
  container_body_inputs: {
    width: width * 0.85,
    // height: height * 0.5,
    // justifyContent: 'space-around',
    // borderWidth:.2,
    // backgroundColor: 'green',
    marginTop: height * 0.01,
  },
  container_body_inputs_general: {
    backgroundColor: '#F7F7F8',
    borderColor: '#C7C8CC',
    borderWidth: 1,
    marginTop: 8,
  },
  container_divider: {
    width: width * 0.85,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  container_divider_innput: {
    width: width * 0.4,
  },
  container_divider_space: {
    width: width * 0.85,
    height: height * 0.1,
  },
  container_btn_save: {
    width: width * 0.85,
    height: height * 0.07,
    backgroundColor: general.secondaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
  },
  container_btn_save_text: {
    color: general.textButtons,
    fontSize: 15,
  },
});

const PerfilS = StyleSheet.create({
  container: {
    flex: 1,
    width: width * 1,
    backgroundColor: '#ffff',
    justifyContent: 'center',
  },

  container_body: {
    width: width * 0.9,
    height: height * 0.6,
    alignSelf: 'center',
    // backgroundColor: 'red',
  },

  container_head: {
    width: width * 0.9,
    height: height * 0.1,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    // backgroundColor: 'green',
  },
  size_image: {
    width: width * 0.3,
    height: height * 0.16,
    borderRadius: 100,
  },
  container_head_icon: {
    backgroundColor: general.colorTextos,
    width: width * 0.3,
    height: height * 0.06,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 7,
    left: 10,
  },
  container_body_center: {
    width: width * 0.85,
    height: height * 0.5,
    flexDirection: 'column',
    justifyContent: 'space-around',
    // alignItems: 'center',
    alignSelf: 'center',
    // borderColor: 'purple',
    // borderWidth: 1,
  },
  container_btn_save: {
    width: width * 0.85,
    height: height * 0.07,
    backgroundColor: general.secondaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  container_btn_save_text: {
    color: general.textButtons,
    fontSize: 15,
  },
  //  MODAL GENERAL
  menu_modal_container: {
    backgroundColor: 'white',
    width: width * 0.9,
    height: height * 0.55,
    alignSelf: 'center',
    justifyContent: 'space-around',
    // alignItems: 'center',
    flexDirection: 'column',
    padding: 20,
    borderRadius: 5,
  },
  menu_modal_container_option: {
    width: width * 0.8,
    height: height * 0.08,
    backgroundColor: general.backgroundInputsForms,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: height * 0.005,
    // borderBottomWidth: 1,
    // borderColor: '#D1D1D1',
  },
  menu_modal_container_option1: {
    width: width * 0.8,
    height: height * 0.08,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.005,
    backgroundColor: general.secondaryColor,

    //  borderTopWidth: 1,
    //  borderColor: '#D1D1D1',
  },
  menu_modal_container_option2: {
    width: width * 0.35,
    height: height * 0.07,
    // backgroundColor: '#FF5656',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.001,
    borderRadius: 4,
    borderWidth: 0.7,
    borderBottomWidth: 1,
    borderColor: '#D1D1D1',
  },
});

const ListadoS = StyleSheet.create({
  container: {
    flex: 1,
    width: width * 1,
    backgroundColor: '#ffff',
    // justifyContent: 'center',
    alignItems: 'center',
  },
  container_body: {
    height: height * 0.75,
    width: width * 0.9,
    // backgroundColor: '#E2DFD0',
    // borderWidth: 1,
  },
  container_count: {
    height: height * 0.06,
    width: width * 1,
    marginBottom: height * 0.02,
    // backgroundColor: '#E2DFD0',
  },
  container_count_body: {
    height: height * 0.04,
    width: width * 1,
    backgroundColor: '#FF9E14',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container_count_text: {
    color: 'white',
    fontSize: 15,
    fontWeight: '600',
  },
  accordion: {
    height: height * 0.27,
    width: width * 0.9,
    backgroundColor: '#F7F7F8',
    flexDirection: 'column',
    marginBottom: 5,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderWidth: 1,
    borderColor: general.bordercolorInputsForms,
  },
  accordion_div: {
    height: height * 0.23,
    width: width * 0.9,
    // backgroundColor: '#ff0',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  accordion_footer: {
    height: height * 0.03,
    width: width * 0.85,
    // backgroundColor: 'red',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  accordion_footer_button: {
    height: height * 0.03,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    // backgroundColor: 'red',
  },
  accordion_group_left: {
    height: height * 0.22,
    width: width * 0.3,
    // backgroundColor: '#524C42',
    flexDirection: 'column',
    justifyContent: 'space-around',
  },
  accordion_group_right: {
    height: height * 0.22,
    width: width * 0.5,
    // backgroundColor: '#F3D0D7',
    flexDirection: 'column',
    justifyContent: 'space-around',
  },
  text_bolder: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#393E46',
  },
  text_description: {
    fontSize: 14,
    fontWeight: '500',
    color: '#686D76',
  },
});

const HistorialS = StyleSheet.create({
  container: {
    flex: 1,
    width: width * 1,
    backgroundColor: '#ffff',
    justifyContent: 'center',
    alignItems: 'center',
  },

  container_head: {
    height: height * 0.1,
    width: width * 0.9,
    //  backgroundColor: '#E2DFD0',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderColor: general.colorbuttons,
    marginBottom: 10,
  },
  container_head_search: {
    height: height * 0.07,
    width: width * 0.4,
    flexDirection: 'row',
    borderColor: general.colorLables,
    borderWidth: 0.7,
    justifyContent: 'space-around',
    alignItems: 'center',
    //  borderWidth: 1,
    borderRadius: 5,
  },
  container_head_time: {
    height: height * 0.07,
    width: width * 0.3,
    flexDirection: 'row',
    borderColor: general.colorLables,
    borderWidth: 0.7,
    justifyContent: 'space-around',
    alignItems: 'center',
    borderRadius: 5,
  },
  container_head_options: {
    height: height * 0.07,
    width: width * 0.1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container_body: {
    height: height * 0.7,
    width: width * 0.9,
  },
  accordion: {
    height: height * 0.27,
    width: width * 0.9,
    backgroundColor: '#F7F7F8',
    flexDirection: 'column',
    marginBottom: 5,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderWidth: 1,
    borderColor: general.bordercolorInputsForms,
  },
  accordion_div: {
    height: height * 0.23,
    width: width * 0.9,
    // backgroundColor: '#ff0',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  accordion_footer: {
    height: height * 0.03,
    width: width * 0.85,
    // backgroundColor: 'red',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  accordion_footer_button: {
    height: height * 0.03,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    // backgroundColor: 'red',
  },
  accordion_group_left: {
    height: height * 0.22,
    width: width * 0.3,
    // backgroundColor: '#524C42',
    flexDirection: 'column',
    justifyContent: 'space-around',
  },
  accordion_group_right: {
    height: height * 0.22,
    width: width * 0.5,
    // backgroundColor: '#F3D0D7',
    flexDirection: 'column',
    justifyContent: 'space-around',
  },

  text_bolder: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#393E46',
  },
  text_description: {
    fontSize: 14,
    fontWeight: '500',
    color: '#686D76',
  },
  //  MODAL GENERAL
  menu_modal_container: {
    backgroundColor: 'white',
    width: width * 0.75,
    height: height * 0.35,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    padding: 20,
    borderRadius: 5,
  },
  menu_modal_container_option: {
    width: width * 0.75,
    height: height * 0.08,
    backgroundColor: general.backgroundInputsForms,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.005,
    borderBottomWidth: 1,
    borderColor: '#D1D1D1',
  },
  menu_modal_container_option1: {
    width: width * 0.75,
    height: height * 0.08,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.005,
    backgroundColor: general.backgroundInputsForms,

    //  borderTopWidth: 1,
    //  borderColor: '#D1D1D1',
  },
  menu_modal_container_option2: {
    width: width * 0.75,
    height: height * 0.08,
    // backgroundColor: '#FF5656',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.001,
  },
  color_buttons: {
    color: general.colorLables,
  },
});

const ReportesS = StyleSheet.create({
  container: {
    flex: 1,
    width: width * 1,
    backgroundColor: '#ffff',
    justifyContent: 'center',
    alignItems: 'center',
  },

  container_head: {
    height: height * 0.1,
    width: width * 0.9,
    //  backgroundColor: '#E2DFD0',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderColor: general.colorbuttons,
    marginBottom: 10,
  },
  container_head_search: {
    height: height * 0.07,
    width: width * 0.4,
    flexDirection: 'row',
    borderColor: general.colorLables,
    borderWidth: 0.7,
    justifyContent: 'space-around',
    alignItems: 'center',
    //  borderWidth: 1,
    borderRadius: 5,
  },
  container_head_time: {
    height: height * 0.07,
    width: width * 0.3,
    flexDirection: 'row',
    borderColor: general.colorLables,
    borderWidth: 0.7,
    justifyContent: 'space-around',
    alignItems: 'center',
    //  borderWidth: 1,
    borderRadius: 5,
  },
  container_head_options: {
    height: height * 0.07,
    width: width * 0.1,
    //  backgroundColor: '#f3d',
    justifyContent: 'center',
    alignItems: 'center',
    //  borderWidth: 1,
  },
  container_body: {
    height: height * 0.7,
    width: width * 0.9,
    justifyContent: 'center',
    alignItems: 'center',
    //  borderWidth: 1,
  },
  accordion: {
    height: height * 0.27,
    width: width * 0.9,
    backgroundColor: '#F7F7F8',
    flexDirection: 'column',
    marginBottom: 5,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderWidth: 1,
    borderColor: general.bordercolorInputsForms,
  },
  accordion_div: {
    height: height * 0.23,
    width: width * 0.9,
    // backgroundColor: '#ff0',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  accordion_footer: {
    height: height * 0.03,
    width: width * 0.85,
    // backgroundColor: 'red',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  accordion_footer_button: {
    height: height * 0.03,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    // backgroundColor: 'red',
  },
  accordion_group_left: {
    height: height * 0.22,
    width: width * 0.3,
    // backgroundColor: '#524C42',
    flexDirection: 'column',
    justifyContent: 'space-around',
  },
  accordion_group_right: {
    height: height * 0.22,
    width: width * 0.5,
    // backgroundColor: '#F3D0D7',
    flexDirection: 'column',
    justifyContent: 'space-around',
  },

  text_bolder: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#393E46',
  },
  text_description: {
    fontSize: 14,
    fontWeight: '500',
    color: '#686D76',
  },
  //  MODAL GENERAL
  menu_modal_container: {
    backgroundColor: 'white',
    width: width * 0.75,
    height: height * 0.35,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    padding: 20,
    borderRadius: 5,
  },
  menu_modal_container_option: {
    width: width * 0.75,
    height: height * 0.08,
    backgroundColor: general.backgroundInputsForms,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.005,
    borderBottomWidth: 1,
    borderColor: '#D1D1D1',
  },
  menu_modal_container_option1: {
    width: width * 0.75,
    height: height * 0.08,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.005,
    backgroundColor: general.backgroundInputsForms,

    //  borderTopWidth: 1,
    //  borderColor: '#D1D1D1',
  },
  menu_modal_container_option2: {
    width: width * 0.75,
    height: height * 0.08,
    // backgroundColor: '#FF5656',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.001,
  },
  color_buttons: {
    color: general.colorLables,
  },
});

const ListadoDetalleS = StyleSheet.create({
  container: {
    flex: 1,
    width: width * 1,
    backgroundColor: '#ffff',
    // justifyContent: 'center',
  },
  text_color_general: {
    color: general.colorTextos,
    fontSize: 14,
    fontWeight: '500',
  },
  container_head: {
    width: width * 0.85,
    height: height * 0.08,
    marginTop: height * 0.02,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignSelf: 'center',
    borderBottomWidth: 1,
    borderBottomColor: general.colorbuttons,
    // backgroundColor: 'red',
  },
  container_head_div: {
    width: width * 0.93,
    height: height * 0.06,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  container_menu_options_head: {
    width: width * 0.12,
    height: height * 0.06,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  text_title_head: {
    fontSize: 18,
    fontWeight: '700',
    color: general.colorTextos,
  },
  container_name_user: {
    width: width * 0.95,
    height: height * 0.05,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },

  container_name_user_div: {
    width: width * 0.93,
    height: height * 0.05,
    flexDirection: 'row',
    // justifyContent: 'space-around',
    alignItems: 'center',
  },

  container_body: {
    width: width * 0.95,
    height: height * 0.7,
    // backgroundColor: '#f19fff',
    alignSelf: 'center',
    alignItems: 'center',

    marginTop: height * 0.02,
  },
  container_body_inputs: {
    width: width * 0.85,
    // height: height * 0.5,
    // justifyContent: 'space-around',
    // borderWidth:.2,
    // backgroundColor: 'green',
    marginTop: height * 0.01,
  },
  container_body_inputs_general: {
    backgroundColor: '#F7F7F8',
    borderColor: '#C7C8CC',
    borderWidth: 1,
    marginTop: 8,
  },
  container_divider: {
    width: width * 0.85,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  container_divider_innput: {
    width: width * 0.4,
  },
  container_divider_space: {
    width: width * 0.85,
    height: height * 0.1,
  },
  container_btn_save: {
    width: width * 0.85,
    height: height * 0.07,
    backgroundColor: general.secondaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
  },
  container_btn_save_text: {
    color: general.textButtons,
    fontSize: 15,
  },
  container_head_search: {
    height: height * 0.07,
    width: width * 0.85,
    flexDirection: 'row',
    backgroundColor: '#F7F7F8',
    borderColor: '#C7C8CC',
    borderWidth: 0.8,
    borderBottomWidth: 2,
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: height * 0.01,
    //  borderWidth: 1,
    borderRadius: 5,
  },
  menu_modal_container: {
    backgroundColor: 'white',
    width: width * 0.75,
    height: height * 0.34,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    // padding: 20,
    borderRadius: 5,
  },
  menu_modal_container_option: {
    width: width * 0.75,
    height: height * 0.08,
    backgroundColor: '#F5F5F5',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.005,
    borderBottomWidth: 1,
    borderBottomColor: general.bordercolorInputsForms,
  },
  menu_modal_container_option1: {
    width: width * 0.75,
    height: height * 0.08,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.005,
    // borderTopWidth: 1,
    backgroundColor: '#F5F5F5',
    borderColor: '#D1D1D1',
  },
  menu_modal_container_option2: {
    width: width * 0.75,
    height: height * 0.08,
    // backgroundColor: '#FF5656',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.001,
  },
  color_buttons: {
    color: general.colorLables,
    fontSize: 15,
  },
});

export {
  LoginS,
  InicioS,
  CotizarS,
  PerfilS,
  ListadoS,
  HistorialS,
  ReportesS,
  ListadoDetalleS,
};
